import {
  IconAlertTriangle,
  IconArrowsMinimize,
  IconBrandGithub,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCircleX,
  IconCopy,
  IconDeviceDesktop,
  IconDownload,
  IconDroplet,
  IconExternalLink,
  IconFile,
  IconFileExport,
  IconFileInfo,
  IconFileScissors,
  IconFiles,
  IconFileTypePdf,
  IconGripVertical,
  IconInfoCircle,
  IconLanguage,
  IconLayersSubtract,
  IconLink,
  IconMarkdown,
  IconMaximize,
  IconQuote,
  IconLayoutGrid,
  IconListNumbers,
  IconLock,
  IconLockOpen,
  IconMenu2,
  IconMinus,
  IconMoon,
  IconPhoto,
  IconPlus,
  IconRotateClockwise2,
  IconScissors,
  IconSearch,
  IconServer,
  IconSettings,
  IconShieldCheck,
  IconSignature,
  IconSparkles,
  IconSquareRoundedCheck,
  IconSun,
  IconTextScan2,
  IconTrash,
  IconUpload,
  IconUserCheck,
  IconX,
  IconZoomIn,
  IconZoomReset,
} from "@tabler/icons-react";

const DEFAULT_STROKE = 2;

export function PdfinIcon({ icon: Icon, size = 18, stroke = DEFAULT_STROKE, "aria-hidden": ariaHidden = true, ...props }) {
  return <Icon size={size} stroke={stroke} aria-hidden={ariaHidden} {...props} />;
}

const makeIcon = (Icon) => (size = 18, props = {}) => <PdfinIcon icon={Icon} size={size} {...props} />;

export const Icons = {
  alert: makeIcon(IconAlertTriangle),
  check: makeIcon(IconCircleCheck),
  tick: makeIcon(IconCheck),
  checkMark: makeIcon(IconSquareRoundedCheck),
  chevDown: makeIcon(IconChevronDown),
  chevLeft: makeIcon(IconChevronLeft),
  chevRight: makeIcon(IconChevronRight),
  chevUp: makeIcon(IconChevronUp),
  copy: makeIcon(IconCopy),
  desktop: makeIcon(IconDeviceDesktop),
  download: makeIcon(IconDownload),
  error: makeIcon(IconCircleX),
  external: makeIcon(IconExternalLink),
  file: makeIcon(IconFile),
  filePdf: makeIcon(IconFileTypePdf),
  github: makeIcon(IconBrandGithub),
  grip: makeIcon(IconGripVertical),
  info: makeIcon(IconInfoCircle),
  language: makeIcon(IconLanguage),
  link: makeIcon(IconLink),
  maximize: makeIcon(IconMaximize),
  menu: makeIcon(IconMenu2),
  quote: makeIcon(IconQuote),
  minus: makeIcon(IconMinus),
  moon: makeIcon(IconMoon),
  plus: makeIcon(IconPlus),
  privacy: makeIcon(IconShieldCheck),
  search: makeIcon(IconSearch),
  server: makeIcon(IconServer),
  settings: makeIcon(IconSettings),
  sparkle: makeIcon(IconSparkles),
  sun: makeIcon(IconSun),
  trash: makeIcon(IconTrash),
  upload: makeIcon(IconUpload),
  userCheck: makeIcon(IconUserCheck),
  x: makeIcon(IconX),
  zoomIn: makeIcon(IconZoomIn),
  zoomReset: makeIcon(IconZoomReset),
};

export const toolIcons = {
  merge: makeIcon(IconFiles),
  split: makeIcon(IconFileScissors),
  organize: makeIcon(IconLayoutGrid),
  rotate: makeIcon(IconRotateClockwise2),
  compress: makeIcon(IconArrowsMinimize),
  watermark: makeIcon(IconDroplet),
  img2pdf: makeIcon(IconPhoto),
  pdf2img: makeIcon(IconFileExport),
  md2pdf: makeIcon(IconMarkdown),
  pagenum: makeIcon(IconListNumbers),
  flatten: makeIcon(IconLayersSubtract),
  protect: makeIcon(IconLock),
  unlock: makeIcon(IconLockOpen),
  metadata: makeIcon(IconFileInfo),
  sign: makeIcon(IconSignature),
  ocr: makeIcon(IconTextScan2),
};

export const splitModeIcons = {
  range: makeIcon(IconScissors),
  selected: makeIcon(IconSquareRoundedCheck),
  every: makeIcon(IconListNumbers),
};

export function toolIcon(id, size = 18, props = {}) {
  return (toolIcons[id] || toolIcons.merge)(size, props);
}
